name: multiple_result_alias
description: Provide aliases for multiple_result package to avoid name conflicts.
version: 5.2.0
repository: https://github.com/DIG-/dart-multiple-result-alias
topics:
  - result
  - utility

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  multiple_result: ^5.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
