name: multiple_result_alias
description: Aliases for multiple_result package
version: 0.0.1
repository: https://github.com/DIG-/dart-multiple-result-alias
topics:
  - result
  - utility

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  multiple_result: ^5.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
